FROM node:12-slim

RUN mkdir -p /home/node/frontend/node_modules && chown -R node:node /home/node/frontend

WORKDIR /home/node/frontend

COPY package*.json ./

USER node

RUN npm install --production

COPY --chown=node:node . .

CMD [ "npm", "run", "next"]
