version: "3"
services:
  backend:
    container_name: express-server
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ./backend:/home/node/app
    ports:
      - "4000:4000"
    command: npm run dev
    networks:
      back-tier:

  frontend:
    container_name: nextjs-frontend
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ./frontend:/home/node/frontend
    expose:
      - "3000"
    networks:
      back-tier:
    environment:
      - HOST_API=backend

  nginx:
    image: nginx:alpine
    container_name: web_server_nginx
    volumes:
      - ./backend/src/config/nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./frontend/landpage:/srv
    ports:
      - 80:80
    networks:
      back-tier:

  mycron:
    container_name: cron-service
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile.dev
    entrypoint: sh /home/node/app/crontab.sh
    networks:
      back-tier:

networks:
  back-tier:
    driver: bridge

