version: "3"
services:
  app:
    container_name: puppeteer-container
    build:
      context: "."
      dockerfile: "./Dockerfile"
    volumes:
      - /app:/app
    expose:
      - "4000"
    ports:
      - "3000:3000"
      - "4000:4000"