version: "3"
services:
  backend:
    container_name: express-server
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    ports:
      - "4000:4000"
    networks:
      back-tier:

  frontend:
    container_name: nextjs-frontend
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    networks:
      back-tier:

  nginx:
    image: nginx:alpine
    container_name: web_server_nginx
    volumes:
      - ./backend/src/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/landpage:/srv
    ports:
      - 80:80
    networks:
      back-tier:

  mycron:
    container_name: cron-service
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    entrypoint: sh /home/node/app/crontab.sh

networks:
  back-tier:
    driver: bridge

