
# serverless.yml

service: emailScrapper

app: email-scrapper
org: sebas119


provider:
  name: aws
  region: us-east-1
  versionFunctions: false
  layers:
    # https://github.com/shelfio/chrome-aws-lambda-layer
    - arn:aws:lambda:${self:provider.region}:764866452798:layer:chrome-aws-lambda:10
  # function parameters
  runtime: nodejs12.x
  memorySize: 2048 # recommended
  timeout: 30
  cfnRole: arn:aws:iam::880273245765:role/sebas119-sls

functions:
  unMejorEmpleoScrapper:
    handler: src/index.handler
    timeout: 900